version: "3"

services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    build: .
    volumes:
      - "./data:/data"
      # - "./index:/data/.flatnotes"  # Optional
    ports:
      - "80:80"
    restart: unless-stopped
